# Generated by Django 3.1 on 2022-05-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_address_line_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_line_1',
            new_name='address_line',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='state',
            new_name='province',
        ),
    ]
